services:
  core-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${CORE_DB_NAME}
      POSTGRES_USER: ${CORE_DB_USER}
      POSTGRES_PASSWORD: ${CORE_DB_PASSWORD}
    ports: [ "${CORE_DB_PORT:-5432}:5432" ]
    volumes: [ "core_pg_data:/var/lib/postgresql/data" ]

  analyser-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${ANALYSER_DB_NAME}
      POSTGRES_USER: ${ANALYSER_DB_USER}
      POSTGRES_PASSWORD: ${ANALYSER_DB_PASSWORD}
    ports: [ "${ANALYSER_DB_PORT:-5433}:5432" ]
    volumes: [ "analyser_pg_data:/var/lib/postgresql/data" ]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start-dev --import-realm --http-port=8180
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_URL_PROPERTIES: "?allowPublicKeyRetrieval=true&useSSL=false"
    ports: [ "${KEYCLOAK_PORT:-8180}:8180" ]
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-import.json

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes: [ "rabbitmq_data:/var/lib/rabbitmq" ]


#  redis:


volumes:
  core_pg_data:
  analyser_pg_data:
  keycloak_data:
  rabbitmq_data: